theme: minima

title: かける族のウェブサイト
author: Python/Scratchユーザー - kakeruzoku@gmail.com / @kakeruzoku

description: >
  Pythonしかまともにプログラミングできない受験生(中3)
  最近Javascriptもやってるらしい

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: classic