theme: minima

title: かける族のウェブサイト
author: Python/Scratchユーザー - kakeruzoku@gmail.com / @kakeruzoku

description: 受験生なう

header_pages:
  - about.md
  - discord/index.md
  - discord/bot/index.md
  - scratch/Scratchattach.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: classic