theme: minima

title: かける族のウェブサイト
author:
  name: Python / Scratch User
  email: kakeruzoku@gmail.com

description: >
  Pythonしかまともにプログラミングできない受験生(中3)
  最近Javascriptもやってるらしい

plugins:
  - jekyll-feed
  - jekyll-seo-tag

minima:
  skin: classic